Gui:
    Game Name: "Pro Evolution Soccer 2014 - PSP - ULES01598 - database_s"

Game Data:
    Total Stadiums: 17
    Stadium Name Lenght : 61
    Total Leagues: 16
    Total Teams: 358
    Total Nationalities: 143
    Total Balls: 25
    Base Address: 0x88036ec

SLXX Offsets:
    Balls Offsets Table: 0x2a24a0
    Balls Text Data Offset: 0x2a2348
    Balls Text Data Size: 0x158

DATABASE_X Offsets:
    Teams Offsets Table: 0x3288
    Teams Text Data Offset: 0x1180
    Teams Text Data Size: 0x1fe0

    Nationalities Offsets Table: 0xd08
    Nationalities Text Data Offset: 0x80
    Nationalities Text Data Size: 0xc88

DEFAULT_DATASET Offsets:
    Stadiums Offsets Table 1: 0x961a0
    Stadiums Offsets Table 2: 0x96600
    Leagues Offsets Table 1: 0x96ab0
    Leagues Offsets Table 2: 0x96ab0

Callnames:
    Name Lenght: 0x30
    Encoding: "utf8"
