Gui:
    Game Name: "Pro Evolution Soccer 2011 - PS2 - SLES_556.36"

Game Data:
    Total Stadiums: 26
    Stadium Name Lenght : 61
    Total Leagues: 16
    Total Teams: 354
    Total Nationalities: 142
    Total Balls: 22
    Base Address: 0xff000

SLXX Offsets:
    Balls Offsets Table: 0x324820
    Balls Offsets Size: 0x08
    Balls Text Data Offset: 0x324640
    Balls Text Data Size: 0x1e0

DATABASE_OVL Offsets:
    "database_e.ovl":
        Teams Offsets Table: 0x3650
        Teams Text Data Offset: 0x11a0
        Teams Text Data Size: 0x2270

        Nationalities Offsets Table: 0xd30
        Nationalities Text Data Offset: 0x100
        Nationalities Text Data Size: 0xc30

DEFAULT_DATASET Offsets:
    Stadiums Offsets Table 1: 0x9b9b0
    Stadiums Offsets Table 2: 0x9c040
    Leagues Offsets Table 1: 0x9c720
    Leagues Offsets Table 2: 0x9c720

Callnames:
    Name Lenght: 0x30
    Encoding: "utf8"
